// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"example/go_backoffice/controllers"
	"example/go_backoffice/repositories"
	"example/go_backoffice/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserController(db *gorm.DB) *controllers.UserController {
	userRepo := repositories.NewUserRepository(db)
	scopeRepo := repositories.NewScopeRepository(db)
	userService := services.NewUserService(userRepo, scopeRepo)
	userController := controllers.NewUserController(userService)
	return userController
}

func InitAgentController(db *gorm.DB) *controllers.AgentController {
	userRepo := repositories.NewUserRepository(db)
	scopeRepo := repositories.NewScopeRepository(db)
	userService := services.NewUserService(userRepo, scopeRepo)
	agentNodeRepo := repositories.NewAgentNodeRepository(db)
	agentNodeService := services.NewAgentNodeService(agentNodeRepo, scopeRepo)
	agentController := controllers.NewAgentController(userService, agentNodeService)
	return agentController
}

func InitAuthController(db *gorm.DB) *controllers.AuthController {
	userRepo := repositories.NewUserRepository(db)
	authService := services.NewAuthService(userRepo)
	authController := controllers.NewAuthController(authService)
	return authController
}

func InitAgentOperatorController(db *gorm.DB) *controllers.AgentOperatorController {
	agentOperatorRepo := repositories.NewAgentOperatorRepository(db)
	userRepo := repositories.NewUserRepository(db)
	agentOperatorService := services.NewAgentOperatorService(agentOperatorRepo, userRepo)
	agentOperatorController := controllers.NewAgentOperatorController(agentOperatorService)
	return agentOperatorController
}

func InitAgencyOperatorController(db *gorm.DB) *controllers.AgencyOperatorController {
	agencyOperatorRepo := repositories.NewAgencyOperatorRepository(db)
	userRepo := repositories.NewUserRepository(db)
	agencyOperatorService := services.NewAgencyOperatorService(agencyOperatorRepo, userRepo)
	agencyOperatorController := controllers.NewAgencyOperatorController(agencyOperatorService)
	return agencyOperatorController
}
