// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"example/go_backoffice/controllers"
	"example/go_backoffice/policies"
	"example/go_backoffice/repositories"
	"example/go_backoffice/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserController(db *gorm.DB) *controllers.UserController {
	userRepo := repositories.NewUserRepository(db)
	scopeRepo := repositories.NewScopeRepository(db)
	agentNodeRepo := repositories.NewAgentNodeRepository(db)
	agencyPolicy := policies.NewAgencyPolicy(agentNodeRepo)
	scopePolicy := policies.NewScopePolicy(scopeRepo, agentNodeRepo)
	userService := services.NewUserService(userRepo, scopeRepo, agencyPolicy, scopePolicy)
	userController := controllers.NewUserController(userService)
	return userController
}

func InitAgentController(db *gorm.DB) *controllers.AgentController {
	userRepo := repositories.NewUserRepository(db)
	scopeRepo := repositories.NewScopeRepository(db)
	agentNodeRepo := repositories.NewAgentNodeRepository(db)
	agencyPolicy := policies.NewAgencyPolicy(agentNodeRepo)
	scopePolicy := policies.NewScopePolicy(scopeRepo, agentNodeRepo)
	userService := services.NewUserService(userRepo, scopeRepo, agencyPolicy, scopePolicy)
	agentPolicy := policies.NewAgentPolicy(agentNodeRepo)
	agentNodeService := services.NewAgentNodeService(agentNodeRepo, scopeRepo, agentPolicy, scopePolicy)
	agentController := controllers.NewAgentController(userService, agentNodeService)
	return agentController
}

func InitAuthController(db *gorm.DB) *controllers.AuthController {
	userRepo := repositories.NewUserRepository(db)
	authService := services.NewAuthService(userRepo)
	authController := controllers.NewAuthController(authService)
	return authController
}
