// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"example/go_backoffice/controllers"
	"example/go_backoffice/repositories"
	"example/go_backoffice/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitUserController dichiara la catena di dipendenze
func InitUserController(db *gorm.DB) *controllers.UserController {
	userRepo := repositories.NewUserRepository(db)
	agentNodeRepo := repositories.NewAgentNodeRepository(db)
	userService := services.NewUserService(userRepo, agentNodeRepo)
	userController := controllers.NewUserController(userService)
	return userController
}
